apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-config
  namespace: tracing-system
data:
  LISTEN_ADDR: ":4318"
  GRPC_ADDR: ":4317"
  TRACE_TTL: "1h"
  HTTP_READ_HEADER_TIMEOUT: "5s"
  HTTP_READ_TIMEOUT: "15s"
  HTTP_WRITE_TIMEOUT: "30s"
  HTTP_IDLE_TIMEOUT: "60s"
