apiVersion: v1
kind: Service
metadata:
  name: {{ include "tracing.fullname" . }}-web
spec:
  type: {{ .Values.web.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "tracing.name" . }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.web.service.port }}
      targetPort: http
